### ISSUE TITLE
2 copies of downloaded video (unfortunately!) appear within /library

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#45] opened 2023-11-16 01:06 UTC
@deldesir disk space is being wasted at the moment: can you investigate?

![image](https://github.com/iiab/calibre-web/assets/2458907/d37d6fa6-5d63-4716-9934-1801c31815cc)

**Comment by deldesir** [comment] 2023-11-16 01:11
I guess the answer might reside in the dates. The downloads seems from Nov 13 and 15 respectively.

**Comment by deldesir** [comment] 2023-11-16 01:29
I see. Once the file is copied to /library/calibre-web, we need to get rid of the original one.

**Comment by holta** [comment] 2023-11-16 02:18
> I see. We can just rename and move the file.

Sound right.

Please after figuring this out, try to ensure this does not happen again.

(As accidentally bloating people's disks, slowing down their servers, and doing long-term to their microSD cards' longevity is... quite serious.)

**Comment by EMG70** [comment] 2023-11-16 17:42
Latest 
![Screenshot from 2023-11-16 17-40-45](https://github.com/iiab/calibre-web/assets/52469992/65d33476-88c0-4b0b-bd18-e2ca5f975e6d)
![Screenshot from 2023-11-16 17-40-21](https://github.com/iiab/calibre-web/assets/52469992/76d0c5fd-df1c-4e2c-abc3-0aee5a357ec9)

**Comment by EMG70** [comment] 2023-11-16 17:44
![Screenshot from 2023-11-16 17-44-34](https://github.com/iiab/calibre-web/assets/52469992/25035e14-998e-44ac-a174-21feace048b4)
![Screenshot from 2023-11-16 17-43-50](https://github.com/iiab/calibre-web/assets/52469992/87ee538d-1b0d-4391-8830-034f153272d8)

**Comment by EMG70** [comment] 2023-11-16 17:49
![Screenshot from 2023-11-16 17-49-37](https://github.com/iiab/calibre-web/assets/52469992/9cda7aab-bed9-46d8-b035-4d4055f8a242)

**Comment by holta** [comment] 2023-11-16 17:50
Thanks @EMG70 for having reproduced to bug 💯

**Comment by holta** [comment] 2023-12-26 14:35
What video filenames end up in /library/downloads/calibre-web/ and why?

Answers are starting to emerge here:

- [#77](https://github.com/iiab/calibre-web/issues/77#issuecomment-1869102723)

**Comment by holta** [comment] 2023-12-26 15:06
> Contents of the 2 files are indeed identical however, as confirmed by:
> 
> ```
> root@box:~# sha256sum /library/downloads/calibre-web/Youtube/Dua_Lipa/Dua_Lipa_-_Houdini_Official_Music_Video_28.09M_\[suAR1PYFNYA\].webm
> 1d6f546a94e16a728b53b8ec8f358a44e3c7f7390d2712347aef20d060184c64  /library/downloads/calibre-web/Youtube/Dua_Lipa/Dua_Lipa_-_Houdini_Official_Music_Video_28.09M_[suAR1PYFNYA].webm
> 
> root@box:~# sha256sum /library/calibre-web/Dua\ Lipa/Dua\ Lipa\ -\ Houdini\ \(Official\ Music\ Video\)\ \(1\)/Dua\ Lipa\ -\ Houdini\ \(Official\ Music\ Video\)\ -\ Dua\ Lipa.webm
> 1d6f546a94e16a728b53b8ec8f358a44e3c7f7390d2712347aef20d060184c64  /library/calibre-web/Dua Lipa/Dua Lipa - Houdini (Official Music Video) (1)/Dua Lipa - Houdini (Official Music Video) - Dua Lipa.webm
> ```

@deldesir can you explain why exactly 2 copies of every video are being written to the filesystem?

I do not like this, as it permanently damages (wears out) SD cards in low-income communities, even if duplicate file is later deleted 🙃

@chapmanjacobd is it possible our usage below should be slightly changed?  Just if you have a quick moment!

https://github.com/iiab/calibre-web/blob/e83c81e516257ee0625a1aea48a294d95cbcf860/scripts/lb-wrapper#L9

Full excerpt:

```bash
LOG_FILE="/var/log/xklb.log"
XKLB_EXECUTABLE="${XKLB_EXECUTABLE:-lb}"
TMP_DOWNLOADS_DIR="/library/downloads/calibre-web"
SURVEY_DB_FILE="${TMP_DOWNLOADS_DIR}/survey.db"
URL="$1"
FORMAT_OPTIONS="--format best --format-sort 'tbr~1000'"
XKLB_FULL_CMD="${XKLB_EXECUTABLE} tubeadd ${SURVEY_DB_FILE} ${URL} --verbose && ${XKLB_EXECUTABLE} dl ${SURVEY_DB_FILE} --prefix ${TMP_DOWNLOADS_DIR} --write-thumbnail ${FORMAT_OPTIONS} --video ${URL} --verbose"
```

**Comment by chapmanjacobd** [comment] 2023-12-26 15:13
can you run `stat` on those two files?

**Comment by holta** [comment] 2023-12-26 15:23
> can you run `stat` on those two files?

Does the `stat` output at bottom help?

```bash
root@box:~# tree /library/downloads/calibre-web/
/library/downloads/calibre-web/
├── Youtube
│   └── MMTV_NEWLOOK
│       └── URGENT_PANIQUE_CHEZ_FATSHI_COU.P_D_ETAT_EN_COURS_SOULEVEMENT_POPULAIRES_DANS_LA_DIASPORA_15.90k_[vbXu7WaifAo].mp4
└── survey.db
```

```
3 directories, 2 files
root@box:~# tree /library/calibre-web/

/library/calibre-web/
├── MMTV NEWLOOK
│   └── URGENT PANIQUE CHEZ FATSHI,COU.P D'ÉTAT EN COURS, SOULÈVEMENT POPULAIRES DANS LA DIASPORA (1)
│       ├── URGENT PANIQUE CHEZ FATSHI,COU.P D'ÉTAT E - MMTV NEWLOOK.mp4
│       └── cover.jpg
├── config
│   └── app.db
├── metadata.db
└── metadata_db_prefs_backup.json

4 directories, 5 files
```

```
root@box:~# sha256sum /library/downloads/calibre-web/Youtube/MMTV_NEWLOOK/URGENT_PANIQUE_CHEZ_FATSHI_COU.P_D_ETAT_EN_COURS_SOULEVEMENT_POPULAIRES_DANS_LA_DIASPORA_15.90k_\[vbXu7WaifAo\].mp4
847b75333ec4c92da7b575844c7886e13d1cfa4e757ddc23d9f530fcc6156038  /library/downloads/calibre-web/Youtube/MMTV_NEWLOOK/URGENT_PANIQUE_CHEZ_FATSHI_COU.P_D_ETAT_EN_COURS_SOULEVEMENT_POPULAIRES_DANS_LA_DIASPORA_15.90k_[vbXu7WaifAo].mp4
```

```
root@box:~# sha256sum /library/calibre-web/MMTV\ NEWLOOK/URGENT\ PANIQUE\ CHEZ\ FATSHI\,COU.P\ D\'ÉTAT\ EN\ COURS\,\ SOULÈVEMENT\ POPULAIRES\ DANS\ LA\ DIASPORA\ \(1\)/URGENT\ PANIQUE\ CHEZ\ FATSHI\,COU.P\ D\'ÉTAT\ E\ -\ MMTV\ NEWLOOK.mp4
847b75333ec4c92da7b575844c7886e13d1cfa4e757ddc23d9f530fcc6156038  /library/calibre-web/MMTV NEWLOOK/URGENT PANIQUE CHEZ FATSHI,COU.P D'ÉTAT EN COURS, SOULÈVEMENT POPULAIRES DANS LA DIASPORA (1)/URGENT PANIQUE CHEZ FATSHI,COU.P D'ÉTAT E - MMTV NEWLOOK.mp4
```

```
root@box:~# stat /library/downloads/calibre-web/Youtube/MMTV_NEWLOOK/URGENT_PANIQUE_CHEZ_FATSHI_COU.P_D_ETAT_EN_COURS_SOULEVEMENT_POPULAIRES_DANS_LA_DIASPORA_15.90k_\[vbXu7WaifAo\].mp4                                                       File: /library/downloads/calibre-web/Youtube/MMTV_NEWLOOK/URGENT_PANIQUE_CHEZ_FATSHI_COU.P_D_ETAT_EN_COURS_SOULEVEMENT_POPULAIRES_DANS_LA_DIASPORA_15.90k_[vbXu7WaifAo].mp4
  Size: 1033709017      Blocks: 2018976    IO Block: 4096   regular file
Device: 8,1     Inode: 786512      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-12-26 10:18:44.923234248 -0500
Modify: 2023-12-24 11:23:12.000000000 -0500
Change: 2023-12-24 17:36:12.220577366 -0500
 Birth: 2023-12-24 17:36:02.364521938 -0500
```

```root@box:~# stat /library/calibre-web/MMTV\ NEWLOOK/URGENT\ PANIQUE\ CHEZ\ FATSHI\,COU.P\ D\'ÉTAT\ EN\ COURS\,\ SOULÈVEMENT\ POPULAIRES\ DANS\ LA\ DIASPORA\ \(1\)/URGENT\ PANIQUE\ CHEZ\ FATSHI\,COU.P\ D\'ÉTAT\ E\ -\ MMTV\ NEWLOOK.mp4      File: /library/calibre-web/MMTV NEWLOOK/URGENT PANIQUE CHEZ FATSHI,COU.P D'ÉTAT EN COURS, SOULÈVEMENT POPULAIRES DANS LA DIASPORA (1)/URGENT PANIQUE CHEZ FATSHI,COU.P D'ÉTAT E - MMTV NEWLOOK.mp4
  Size: 1033709017      Blocks: 2018976    IO Block: 4096   regular file
Device: 8,1     Inode: 263304      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-12-26 10:19:33.235736751 -0500
Modify: 2023-12-24 17:36:15.428595392 -0500
Change: 2023-12-24 17:36:15.488595729 -0500
 Birth: 2023-12-24 17:36:12.660579839 -0500
```

**Comment by holta** [comment] 2023-12-26 15:25
CORRECTION: Above copy/pastes just cleaned up.

**Comment by chapmanjacobd** [comment] 2023-12-26 15:39
it looks like the

/library/calibre-web/

one is created after the one in the download prefix. 

I imagine this is something calibre is doing when importing the file?

maybe you could download to /tmp or create a hard link or reflink instead of copy.

the xklb settings look ok. But if you aren't using the same xklb database for multiple downloads then you'll need to check if something is already downloaded in the system that calls the lb_wrapper script

**Comment by deldesir** [comment] 2023-12-26 15:53
The second file located at ```/library/calibre-web``` is essentially a duplicate of ```/library/downloads/calibre-web```. The intention behind pull request #47 is to remove the original file after copying and processing it for metadata purposes.

@holta, if you have reservations about the current logic of copying, we can explore a potential solution by considering a rewrite of the uploader code. However, I acknowledge that this might be a complex task, particularly due to Flask's practice of writing uploaded files to temporary locations (https://flask.palletsprojects.com/en/3.0.x/patterns/fileuploads/#improving-uploads). Unless we can find a method for xklb to directly write to /library/calibre-web, bypassing the existing upload mechanism, and subsequently processing metadata.

@chapman, I'm genuinely interested in understanding how xklb handles the saving and naming of video files. I would appreciate your insights on this matter. You can review my attempt to provide clarity to @holta in the discussion [here](https://github.com/iiab/calibre-web/issues/77#issuecomment-1869102723) and [here](https://github.com/iiab/calibre-web/issues/77#issuecomment-1869552964). Your input would be invaluable in addressing any concerns raised.

**Comment by holta** [comment] 2023-12-26 16:04
1) Ok the problem makes more sense now!

- `lb tubeadd` correctly creates `/library/downloads/calibre-web/survey.db`
- `lb dl` correctly downloads video file to `/library/downloads/calibre-web/*.mp4`
- @deldesir's Calibre-Web code is copying `*.mp4` — accidentally creating a duplicate of every video file — when it definitely should be moving not copying (as he indicates above, he's work towards a legit solution!)

2) @chapmanjacobd: if you happen to have a quick answer to what `506` and `510` mean in the *.mp4 filenames below, that'd be awesome, as @deldesir mentions from #77 !  RECAP: The two .mp4 files below were downloaded with the very same xklb command — one right after the other — so the non-deterministic (slightly changing) filename may be harmless but yeah, is a bit mysterious! 😄

```
root@box:~# tree /library/downloads/calibre-web/
/library/downloads/calibre-web/
├── Youtube
│   ├── Himalayan_Trust
│   │   ├── Bringing_technological_literacy_to_Solukhumbu_with_Himalayan_Trust_Nepal_and_Edutech_506.00_[ehSIhj2-qPM].mp4
│   │   ├── Bringing_technological_literacy_to_Solukhumbu_with_Himalayan_Trust_Nepal_and_Edutech_510.00_[ehSIhj2-qPM].mp4
│   │   └── Bringing_technological_literacy_to_Solukhumbu_with_Himalayan_Trust_Nepal_and_Edutech_510.00_[ehSIhj2-qPM].webp
```

**Comment by chapmanjacobd** [comment] 2023-12-26 16:48
By default xklb adds the current video view count to the [output template](https://github.com/yt-dlp/yt-dlp#output-template).

You can override the output template to make it deterministic like so:

```
library download --video test.db https://youtu.be/ehSIhj2-qPM --output '%(id)s.%(ext)s'
```

With the above command the file saved will be `./ehSIhj2-qPM.mkv`

Using `--output` invalidates the `--prefix` sub-command so this will save to the working directory unless you add a directory separator like this: `--output 'folder1/%(id)s.%(ext)s'`

**Comment by holta** [comment] 2023-12-26 16:52
> current video view count

Amazing: Profound thanks @chapmanjacobd for solving the `506` versus `510` riddle four of us were stumped by over recent days!

**Comment by deldesir** [comment] 2023-12-26 17:39
Thank you, @chapmanjacobd, for setting the record straight on how xklb names and saves files. I misunderstood those mysterious dynamic numbers added to the file names, and I appreciate your clarification, explaining that they're in fact current videos view counts, and I appreciate your clarification. Your insights are invaluable as usual, and I acknowledge my error.

**Comment by holta** [comment] 2023-12-31 06:04
This longstanding issue appears solved:

- PR #82

But let's keep it open in early January to validate/confirm ✅ (and refine as necessary!)

**Closed** 2024-02-21 15:00 UTC
Labels: bug, help wanted
