### ISSUE TITLE
Uploading videos via Calibre-Web fails -  500 Internal Server Error

### ISSUE THREAD

**Issue by EMG70** [iiab/calibre-web#203] opened 2024-06-28 14:45 UTC
## Short Notice from the maintainer 

After 6 years of more or less intensive programming on Calibre-Web, I need a break. 
The last few months, maintaining Calibre-Web has felt more like work than a hobby. I felt pressured and teased by people to solve "their" problems and merge PRs for "their" Calibre-Web. 
I have turned off all notifications from Github/Discord and will now concentrate undisturbed on the development of “my” Calibre-Web over the next few weeks/months.  
I will look into the issues and maybe also the PRs from time to time, but don't expect a quick response from me.

Please also have a look at our [Contributing Guidelines](https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md)

**Describe the bug/problem** 

A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

Uploading a 24MB video failed,it returned 500 Internal Server Error.  
Please see https://github.com/iiab/calibre-web/pull/196
**To Reproduce**

1. Go to 'https://www.youtube.com/watch?v=1xhlg9WkPQg'
2. Click on 'Upload'
![Screenshot from 2024-06-28 15-33-39](https://github.com/iiab/calibre-web/assets/52469992/4d0fb390-9ecf-4531-a60d-1069355593d7)

**Logfile**

Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.
[2024-06-28 15:11:52,277] DEBUG {cps.config_sql:407} _ConfigSQL updating storage
[2024-06-28 15:11:52,318]  INFO {cps:172} Starting Calibre Web...
[2024-06-28 15:11:52,329] DEBUG {cps.services:26} Cannot import goodreads, showing authors-metadata will not work: No module named 'goodreads'
[2024-06-28 15:11:52,332] DEBUG {cps.services:34} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2024-06-28 15:11:52,394] DEBUG {cps.services:49} Cannot import gmail, sending books via Gmail Oauth2 Verification will not work: No module named 'google_auth_oauthlib'
[2024-06-28 15:11:52,430]  WARN {py.warnings:112} /usr/local/calibre-web-py3/lib/python3.12/site-packages/flask_limiter/extension.py:337: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(

[2024-06-28 15:11:52,691] DEBUG {cps.gdriveutils:80} Cannot import pydrive, httplib2, using gdrive will not work: No module named 'pydrive'
[2024-06-28 15:11:53,016]  INFO {apscheduler.scheduler:181} Scheduler started
[2024-06-28 15:11:53,017]  INFO {apscheduler.scheduler:895} Added job "delete temp" to job store "default"
[2024-06-28 15:11:53,019]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2024-06-28 15:11:53,020]  INFO {apscheduler.scheduler:895} Added job "immediately delete temp" to job store "default"
[2024-06-28 15:11:53,046]  INFO {apscheduler.executors.default:123} Running job "immediately delete temp (trigger: date[2024-06-28 15:11:53 BST], next run at: 2024-06-28 15:11:53 BST)" (scheduled at 2024-06-28 15:11:53.019999+01:00)
[2024-06-28 15:11:53,047]  INFO {apscheduler.scheduler:641} Removed job f01526ac441841a3ad30ba5ede6a56f3
[2024-06-28 15:11:53,059] DEBUG {cps.services.worker:91} Add Task for user: System - Delete Temp Folder
[2024-06-28 15:11:53,059]  INFO {apscheduler.executors.default:144} Job "immediately delete temp (trigger: date[2024-06-28 15:11:53 BST], next run at: 2024-06-28 15:11:53 BST)" executed successfully
[2024-06-28 15:11:53,299]  WARN {py.warnings:112} /usr/local/calibre-web-py3/cps/uploader.py:338: SyntaxWarning: invalid escape sequence '\,'
  '-vf', 'fps=1,thumbnail,select=gt(scene\,0.1),scale=-1:720',  # apply filters to avoid black frames and scale

[2024-06-28 15:11:53,333] DEBUG {cps.comic:46} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2024-06-28 15:11:53,335] DEBUG {cps.comic:53} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2024-06-28 15:11:53,336] DEBUG {cps.comic:59} Cannot import py7zr, extracting cover files from CB7 files will not work: No module named 'py7zr'
[2024-06-28 15:11:53,515] DEBUG {cps.admin:82} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2024-06-28 15:11:53,525] DEBUG {cps.gdrive:44} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2024-06-28 15:11:53,698] DEBUG {cps.search_metadata:62} Import error for metadata source: douban - No module named 'html2text'
[2024-06-28 15:11:53,726] DEBUG {cps.search_metadata:62} Import error for metadata source: scholar - No module named 'scholarly'
[2024-06-28 15:11:53,727]  WARN {py.warnings:112} /usr/local/calibre-web-py3/cps/metadata_provider/lubimyczytac.py:140: SyntaxWarning: invalid escape sequence '\?'
  characters_to_remove = "\?()\/"

[2024-06-28 15:11:53,749] DEBUG {cps.search_metadata:62} Import error for metadata source: lubimyczytac - No module named 'html2text'
[2024-06-28 15:11:53,752] DEBUG {cps.search_metadata:62} Import error for metadata source: amazon - No module named 'bs4'
[2024-06-28 15:11:53,905]  INFO {cps.server:269} Starting Tornado server on :8083
[2024-06-28 15:13:55,640] DEBUG {cps.web:1434} You are now logged in as: 'Admin'
[2024-06-28 15:13:55,654] DEBUG {cps.ub:82} Login and store session : 325f15e7a1c6d44ea6bc1ac28f970d6e2071c35b5a3d20293ced922c5ee82376fd9c0a53b926819be9cb978b718dcdf8c7a9b990f6731aa25de71acac4f0a718
[2024-06-28 15:13:55,655] DEBUG {cps.ub:84} Found stored session: 325f15e7a1c6d44ea6bc1ac28f970d6e2071c35b5a3d20293ced922c5ee82376fd9c0a53b926819be9cb978b718dcdf8c7a9b990f6731aa25de71acac4f0a718
[2024-06-28 15:14:14,357] DEBUG {cps.uploader:388} Temporary file: /tmp/calibre_web/37c4b0afdc8894ed8554387355402562
[2024-06-28 15:14:14,388]  WARN {cps.uploader:306} Cannot find the xklb database, using default metadata
[2024-06-28 15:14:14,388] ERROR {cps:1414} Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/usermanagement.py", line 34, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 60, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 251, in upload
    meta, error = file_handling_on_upload(requested_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 899, in file_handling_on_upload
    meta = uploader.upload(requested_file, config.config_rarfile_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/uploader.py", line 390, in upload
    return process(tmp_file_path, filename_root, file_extension, rar_excecutable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/uploader.py", line 101, in process
    if not meta.title.strip():
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'title'
[2024-06-28 15:33:19,004] DEBUG {cps.uploader:388} Temporary file: /tmp/calibre_web/37c4b0afdc8894ed8554387355402562
[2024-06-28 15:33:19,076]  WARN {cps.uploader:306} Cannot find the xklb database, using default metadata
[2024-06-28 15:33:19,077] ERROR {cps:1414} Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/usermanagement.py", line 34, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 60, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 251, in upload
    meta, error = file_handling_on_upload(requested_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 899, in file_handling_on_upload
    meta = uploader.upload(requested_file, config.config_rarfile_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/uploader.py", line 390, in upload
    return process(tmp_file_path, filename_root, file_extension, rar_excecutable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/uploader.py", line 101, in process
    if not meta.title.strip():
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'title'
[2024-06-28 15:35:11,771] DEBUG {cps.updater:331} Stable version: {'version': '0.6.22b'}

**Expected behavior**

A clear and concise description of what you expected to happen.Uploaded video is expected to successfully upload 

**Screenshots**

**Environment (please complete the following information):**

 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]
![Screenshot from 2024-06-28 15-41-21](https://github.com/iiab/calibre-web/assets/52469992/3460c8ec-a904-455c-83df-80f537755060)

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by deldesir** [comment] 2024-07-01 14:11
@EMG70, were you trying to upload a video directly from within the YouTube app menu?

**Comment by deldesir** [comment] 2024-07-01 14:20
I just reproduce the issue @EMG70 uploading directly a video using the upload button. I am working on it.

**Comment by EMG70** [comment] 2024-07-01 14:28
> I just reproduce the issue @EMG70 uploading directly a video using the upload button. I am working on it.

Correct,I tried to upload directly using upload button .

**Comment by deldesir** [comment] 2024-07-01 21:01
@EMG70, your upload failed because the video you tried to upload has brackets in its filename...

**Comment by holta** [comment] 2024-07-01 21:28
> upload failed because the video you tried to upload has brackets in its filename

@deldesir which [brackets](https://en.wikipedia.org/wiki/Bracket) are currently not allowed?

![image](https://github.com/iiab/calibre-web/assets/2458907/80992a97-d810-4c52-a5c1-07ae38029a7c)

(How hard is this to fix?!)

**Comment by EMG70** [comment] 2024-07-01 22:06
Thanks @deldesir  and @holta .I have removed square brackets on the video name and managed to upload the video successfully.I will try various brackets tomorrow daytime and upadate you.
![Screenshot from 2024-07-01 23-03-22](https://github.com/iiab/calibre-web/assets/52469992/1b580c77-6f1b-4ab3-976b-b4ffd8add47d)
![Screenshot from 2024-07-01 22-55-58](https://github.com/iiab/calibre-web/assets/52469992/98d00150-9569-4eea-bd25-0e459cb299b5)
![Screenshot from 2024-07-01 22-56-15](https://github.com/iiab/calibre-web/assets/52469992/816ebe83-765b-43b3-88b8-7c1da0ead4e1)

**Comment by EMG70** [comment] 2024-07-01 22:28
name of video prior to editing
![Screenshot from 2024-07-01 23-25-51](https://github.com/iiab/calibre-web/assets/52469992/5d1f1be7-a36d-4df6-b739-01a833dfe8ed)

**Comment by deldesir** [comment] 2024-07-01 22:39
> > upload failed because the video you tried to upload has brackets in its filename
> 
> @deldesir which [brackets](https://en.wikipedia.org/wiki/Bracket) are currently not allowed?
> 
> ![image](https://private-user-images.githubusercontent.com/2458907/344812773-80992a97-d810-4c52-a5c1-07ae38029a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzM2OTgsIm5iZiI6MTcxOTg3MzM5OCwicGF0aCI6Ii8yNDU4OTA3LzM0NDgxMjc3My04MDk5MmE5Ny1kODEwLTRjNTItYTVjMS0wN2FlMzgwMjlhN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMjIzNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQxZDRhYjU4ZWMzNDc3ODQ0ZDZmYTUxNjYxMGEwM2NhOTVmOGE3ZGZlYTMzMTQ3NjA0YmJiZTI1M2RjYzcwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.04OqnvRz5feTh-3pnaNQu27NUnemHjIfAAPeqdB2h44)
> 
> (How hard is this to fix?!)

Square brackets were causing the issue, they are not illegal though. This is now fixed with #208

**Comment by EMG70** [comment] 2024-07-01 22:42
Correct,I have also just confirmed this.
![IMG_3969](https://github.com/iiab/calibre-web/assets/52469992/94a4a834-7c68-402b-b5fb-073fdce53f7d)

**Comment by EMG70** [comment] 2024-07-01 22:44
![Screenshot from 2024-07-01 23-34-27](https://github.com/iiab/calibre-web/assets/52469992/63f85f8b-b82e-4a7f-ad68-b555bdc634bd)
![Screenshot from 2024-07-01 23-36-59](https://github.com/iiab/calibre-web/assets/52469992/16ce9bbb-8349-4c81-802a-75c345469958)
![Screenshot from 2024-07-01 23-38-42](https://github.com/iiab/calibre-web/assets/52469992/7d78c3eb-d031-4b7a-8d90-e1afa7af9752)

**Comment by deldesir** [comment] 2024-07-01 22:45
@EMG70 please try now with the video (or another one) when you have some time. This video must have square brackets in its name.

**Comment by EMG70** [comment] 2024-07-01 22:48
> @EMG70 please try now with the video (or another one) when you have some time. This video must have square brackets in its name.

I guess I will have to do steps for testing a PR#203 right or install new VM if committed or updated on LRN2?

**Comment by deldesir** [comment] 2024-07-01 22:48
You mean PR #208, not #203.

**Comment by EMG70** [comment] 2024-07-01 22:51
> You mean PR #208, not #203. No need to install a new VM. You follow the usual instructions to test a PR.

Sorry meant #208.I will try it.

**Comment by EMG70** [comment] 2024-07-01 23:02
IIAB-DIAGNOSTICS - https://dpaste.com/9F6TFGRCA
Video upload with square brackets GCSE Maths： Introduction to the Playlist [1xhlg9WkPQg].mp4 now working after running PR#208 script.
![Screenshot from 2024-07-01 23-59-22](https://github.com/iiab/calibre-web/assets/52469992/a8f93785-99d4-4010-a9dc-811a6c6f8fb3)

**Comment by deldesir** [comment] 2024-07-01 23:08
Thanks @EMG70. Happy this works now.

**Closed** 2024-07-02 04:48 UTC
Labels: bug

**Comment by holta** [comment] 2024-07-02 04:51
PR #208 is now merged:

Thanks @EMG70 and @deldesir!
